## report merge fields

# FirstName
# LastName
# Fullname
# LastTeam
# DOB
# Age
# Headshot
# Position
# rocketRating
# combineRanking
# collegeHt
# collegeWt
# r_val_Ht_wo_shoes
# r_pct_Ht_wo_shoes
# r_val_StandReach
# r_pct_StandReach
# r_val_Wing
# r_pct_Wing
# r_val_WingHt
# r_pct_Wing_Ht
# r_val_JumpHt
# r_pct_jumpHt
# r_val_standMaxVert
# r_pct_standMaxVert
# r_val_maxVert
# r_pct_MaxVert
# r_val_BW_lbs
# r_pct_BW_lbs
# r_val_Bfat_pct
# r_pct_Bfat_pct
# r_val_HandLen
# r_pct_HandLen
# r_val_HandWid
# r_pct_HandWid
# r_val_LaneShut_R
# r_pct_LaneShut_R
# r_val_LaneShut_L
# r_pct_LaneShut_L
# r_val_LaneAgility
# r_pct_LaneAgility
# r_val_3qrtSpeed
# r_pct_3qrtSpeed
# val_CM_conImp
# pct_CM_comImp
# val_CM_fzero
# pct_CM_fzero
# val_CM_relPP
# pct_CM_relPP
# val_CM_PP
# pct_CM_PP
# val_CM_RSImod
# pct_CM_RSImod
# val_DJ_CT
# pct_DJ_CT
# val_DJ_RSI
# pct_DJ_RSI
# r_val_3qrtRock
# r_pct_3qrtRock
# r_val_QB
# r_pct_QB
# r_val_10m
# r_pct_10m
# r_val_shutLRock
# r_pct_shutLRock
# r_val_shutRRock
# r_pct_shutRRock
# val_imbalance
# pct_imbalance
# val_SL_EccMean
# pct_SL_EccMean
# c_val_Ht_wo_shoes
# c_pct_Ht_wo_shoes
# c_val_StandReach
# c_pct_StandReach
# c_val_Wing
# c_pct_Wing
# c_val_WingHt
# c_pct_Wing_Ht
# c_val_JumpHt
# c_pct_jumpHt
# c_val_standMaxVert
# c_pct_standMaxVert
# c_val_maxVert
# c_pct_MaxVert
# c_val_BW_lbs
# c_pct_BW_lbs
# c_val_Bfat_pct
# c_pct_Bfat_pct
# c_val_HandLen
# c_pct_HandLen
# c_val_HandWid
# c_pct_HandWid
# c_val_LaneShut_R
# c_pct_LaneShut_R
# c_val_LaneShut_L
# c_pct_LaneShut_L
# c_val_LaneAgility
# c_pct_LaneAgility
# c_val_3qrtSpeed
# c_pct_3qrtSpeed